### ISSUE TITLE
CinemachineTargetGroup::RemoveMember loses last array element's value.

### ISSUE THREAD

**Issue by jagendar** [Unity-Technologies/upm-package-cinemachine#12]
Reproduction steps:

Unity 2018.3.7f1
Cinemachine 2.2.8

Create a target group with several elements (3 in my case). 
Call RemoveMember() on the second array element (item @ index 1). 
Note that the item in index 2 doesn't successfully migrate to index 1.

Looking briefly at the code installed with the package, it looks like it's an issue with using the wrong array for determining the length, causing the last value to get dropped from the second copy.

Looking at the code currently in the repository, it looks like it's been updated to account for this issue - but not in the case where the removed item is at the original arraylength - 1 (i.e, a problem with the conditional)

**Comment by glabute** [comment]
I think the current code in the repo is ok.
If the removed item is at position arrayLength-1, then it's the last item, so no elements of the original array that come after it need to be copied over.
Am I missing something here?

**Comment by jagendar** [comment]
Aplogies - You're correct, I mis-typed. Specifically: the issue is with the removing the item at the new array's length - 1, not the original's - or, otherwise, the array length - 2.

Specifically I think this:

`if (index < m_Targets.Length - 1)`

should actually be:

`if(index < oldTargets.Length - 1)`

though I haven't actually pulled the repo to verify the issue, this mistake is actually the same one made by one of my juniors when building a workaround for the initial bug I mentioned above.

**Comment by glabute** [comment]
hah!  You're right!  Thanks Michael :)
