### ISSUE TITLE
CinemachinePath &  CinemachineSmoothPath evaluations difference.

### ISSUE THREAD

**Issue by Azirel** [Unity-Technologies/upm-package-cinemachine#13]
Given.
![image](https://user-images.githubusercontent.com/14969598/54818352-b9133480-4ca1-11e9-978d-cf23e2c22c93.png)
Basicaly we have CinemachinePath &  CinemachineSmoothPath components with same waypoints (zero tangents).
The question is in CinemachinePathBase.EvaluatePosition(float pos). This function gives different values in depend on CinemachinePathBase concete class. It does not seem logical to me. Is it by design or is it a bug? In case if it is made by design, why? And how would I achieve linear interpolation on  position for CinemachinePath?
Test code
```
public class CinemachineEvaluationTest : MonoBehaviour
{
	public Cinemachine.CinemachinePath path;
	public Cinemachine.CinemachineSmoothPath smoothPath;

	[ContextMenu("EvaluationTest")]
	public void EvaluationTest()
	{
		print("CinemachinePath.Evaluation result: " + path.EvaluatePosition(0.77f));
		print("CinemachineSmoothPath.Evaluation result: " + smoothPath.EvaluatePosition(0.77f));
	}
}
```
The result is 
![image](https://user-images.githubusercontent.com/14969598/54819213-d47f3f00-4ca3-11e9-8e39-326a64c1d491.png)

**Comment by glabute** [comment]
The EvaluatePosition API uses native path units, whose interpretation is implementation-dependent.  I think you need to be using the _public Vector3 EvaluatePositionAtUnit(float pos, PositionUnits units)_ API, which can accept path normalized units (0=start of path, 1 = end of path), which are distance-based, and implementation-independent.
