### ISSUE TITLE
dictionary leak in CinemachinePostProcessing

### ISSUE THREAD

**Issue by corngood** [Unity-Technologies/upm-package-cinemachine#3]
We ran https://github.com/Unity-Technologies/ZombieObjectDetector on our project, and it led us to `CinemachinePostProcessing.mBrainToLayer`, which appears to only ever grow:

https://github.com/Unity-Technologies/upm-package-cinemachine/blob/3efa6a34bab4dab766947a2aa35e842e8cbb9873/Runtime/PostProcessing/CinemachinePostProcessing.cs#L207

**Comment by glabute** [comment]
It's true that this only grows, but it's rare to have more than a tiny number of CM brains in a session, so the growth is very limited.  Is this an issue for you that needs resolution?

**Comment by corngood** [comment]
I don't think it's a huge problem, but it depends on the graph of objects that it keeps alive.  It could at least cause fragmentation in normal use of our game (in/out of gameplay, multiple cutscenes, etc).

I'm not sure if ConditionalWeakTable works in unity, but maybe that's an option.

**Comment by Blundig** [comment]
For our project, this was a significant issue.  We load/unload a scene containing a Cinemachine brain and post processing stack often, and each time memory grows.  The requirements for our game are that it must be able to run for weeks, months, or even years without been restarted (it runs on dedicated machines in locations with 24/7 access to players).  So, we can have many brains created and never destroyed during a "session".

I fixed our problem locally by adding a method to CinemachinePostProcessing to manually clear mBrainToLayer.   The game calls it after unloading the scene containing the brain.  This works, but I still vote for having this issue fixed officially in the package in a better way.

**Comment by glabute** [comment]
Thank you both for the feedback.
We have pushed a fix for this onto the CM trunk.  It will be in the final released 2.4.0.
