### ISSUE TITLE
CinemachineTargetGroup moves a transform.

### ISSUE THREAD

**Issue by AndreyPostelzhuk** [Unity-Technologies/upm-package-cinemachine#30]
I'm using `Aim: Group Composer` + `CinemachineTargetGroup` component. I found out that `CinemachineTargetGroup` moves transform it attached too. 
If I disable the `CinemachineTargetGroup` component everything works fine. 
Is this a bug? Or what I'm doing wrong?
cinemachine package version: 2.5.0
unity version: 2019.2.13f1

**Comment by glabute** [comment]
CinemachineTargetGroup component has to be on a different game object.  Set that as as the vcam's target.

**Comment by AndreyPostelzhuk** [comment]
CinemachineTargetGroup IS a different game object with vcam. And CinemachineTargetGroup is a LookAt target. I can export an unitypackage if it's helps.
