### ISSUE TITLE
Can't remove Physics package with Cinemachine installed

### ISSUE THREAD

**Issue by Koopa1018** [Unity-Technologies/upm-package-cinemachine#4]
I'm attempting to clear my Unity project of unneeded native modules. As the project is entirely 2D on the gameplay side, as well as the camera side incidentally, I figured I wouldn't need the Physics package because Physics2D has everything I need.

Unfortunately, when I try to remove it, I get compiler errors from CinemachineCollider.cs, CinemachineOrbitalTransposer.cs, CinemachineTriggerAction.cs, and CinemachineImpulseSource.cs--it seems those files all contain references to components from the Physics module (Collider, Collision, RaycastHit, Rigidbody, etc.). The camera in this project is meant to follow the player in a 2D fashion, so I likely don't need Cinemachine Collider or Orbital Transposer, was wondering: **is it possible to have these modules be excluded if the Physics module is not present?**

And if so, is it a bad idea? Because I'd hate to be one to say "I don't need this, therefore nobody whose circumstances resemble mine is going to need this."

**Comment by glabute** [comment]
This is coming in CM 2.3, to be available for 2019.1 and up.  In the meantime, you can add your own ifdefs for the bits of CM you don't need.

**Comment by Koopa1018** [comment]
Sweet.

So, to be clear, is there an `#if PHYSICS` directive, or something to that effect, in 2018.x? Or should I just use something like `#if false`?

**Comment by glabute** [comment]
You'll have to make your own define.  In 2018 there's no way to tell at compile time if physics.

**Comment by Koopa1018** [comment]
Ah, okay. That's what I was expecting.

Nice that we're getting that feature soon, at least.
Thank you so much for the answers.

**Comment by Koopa1018** [comment]
As of Unity 2019.1.3f1 and CM version 2.3.4, this remains unsolved--all four above-mentioned scripts still error when Physics 3D is removed. Is it still on the roadmap?

**Comment by glabute** [comment]
Yes, unfortunately there is a bug in Unity that is preventing this from working.  The fix in Unity is expected for 2019.3.  The change in CM is just waiting in the wings until then.

**Comment by Koopa1018** [comment]
Huh. Okay then.
