### ISSUE TITLE
CinemachineBrain not updated on UnloadSceneAsync frame

### ISSUE THREAD

**Issue by angusbjones** [Unity-Technologies/upm-package-cinemachine#72]
When two scenes are additively loaded, and then one of those scenes is unloaded using UnloadSceneAsync a CinemachineBrain referencing a VCam in the unloaded scene will only update its' live cam the frame AFTER the unload occurs. This isn't an issue with most blends (except for being a frame behind) but it is for cuts. 

The attached project demonstrates this. Open PrimaryScene and play. SecondaryScene will be loaded additively and its vcam will take priority. SecondaryScene will be unloaded in 2 seconds and Debug.Break will be called directly after this async call. The CinemachineBrain will still be pointing in the same direction and have no Live camera. Stepping to the next frame will show it updated. 
Just to show what is expected, the Loader.cs has a ForceUpdate property that will add a call to CinemachineBrain.ManualUpdate on the sceneUnloaded event. With this property checked the CinemachineBrain behaves as expected. I only used the preview package so I'd have access to CinemachineBrain.ManualUpdate to show this behaviour, the same issue occurs in the verified package.

[CinemachineUnloadSceneExample.zip](https://github.com/Unity-Technologies/upm-package-cinemachine/files/4840103/CinemachineUnloadSceneExample.zip)

**Comment by glabute** [comment]
Thank you for finding that nice little hole, and for your excellent report.
I think adding an automatic update in the brain on scene loaded or unloaded should patch that up.
Best regards!
