### ISSUE TITLE
Is the bugfix #74 exactly correct?

### ISSUE THREAD

**Issue by rigven** [Unity-Technologies/upm-package-cinemachine#78]
I have 3 States and StateDrivenCamera does not switch cameras since `GetClipHash(info.fullPathHash, m_clipInfoList);` returns the wrong hash. 
If I roll back the changes in the ChooseCurrentCamera() function from bugfix #74 , everything works fine thanks to `hash = info.fullPathHash;`

**Comment by glabute** [comment]
I made a state machine with 3 states, and I get the correct results.  Can you give more detailed repro steps, or PM me with a repro project?

**Comment by rigven** [comment]
https://github.com/rigven/Tilevania-Unity2D-course-
Here is the project with the described problem

**Comment by glabute** [comment]
Thank you for the project.  With it, I was able to locate the bug and push a fix.  Best regards
